server:
  port: 9998

spring:
  application:
    name: spring-cloud-feign

#注册中心指向start
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/
#注册中心指向end

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

feign:
  hhystrix:
    enabled: true